import {
  Shirt,
  Smartphone,
  Laptop,
  Sparkles,
  Home,
  Tv,
  Baby,
  Apple,
  Car,
  Dumbbell,
  Sofa,
  BookOpen,
  Bike,
  ShoppingBag,
} from "lucide-react";

export const dummyCategories = [
  {
    _id: "cat-001",
    name: "For You",
    slug: "for-you",
    image: "",
    icon: "shopping-bag",
    sortOrder: 1,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-002",
    name: "Fashion",
    slug: "fashion",
    image: "",
    icon: "shirt",
    sortOrder: 2,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-003",
    name: "Mobiles",
    slug: "mobiles",
    image: "",
    icon: "smartphone",
    sortOrder: 3,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-004",
    name: "Electronics",
    slug: "electronics",
    image: "",
    icon: "laptop",
    sortOrder: 4,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-005",
    name: "Beauty",
    slug: "beauty",
    image: "",
    icon: "sparkles",
    sortOrder: 5,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-006",
    name: "Home",
    slug: "home",
    image: "",
    icon: "home",
    sortOrder: 6,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-007",
    name: "Appliances",
    slug: "appliances",
    image: "",
    icon: "tv",
    sortOrder: 7,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-008",
    name: "Toys & Baby",
    slug: "toys-baby",
    image: "",
    icon: "baby",
    sortOrder: 8,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-009",
    name: "Food & Health",
    slug: "food-health",
    image: "",
    icon: "apple",
    sortOrder: 9,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-010",
    name: "Auto Accessories",
    slug: "auto-accessories",
    image: "",
    icon: "car",
    sortOrder: 10,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-011",
    name: "Sports & Fitness",
    slug: "sports-fitness",
    image: "",
    icon: "dumbbell",
    sortOrder: 11,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-012",
    name: "Furniture",
    slug: "furniture",
    image: "",
    icon: "sofa",
    sortOrder: 12,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-013",
    name: "Books & Media",
    slug: "books-media",
    image: "",
    icon: "book",
    sortOrder: 13,
    isActive: true,
    showInTopNav: true,
  },

  {
    _id: "cat-014",
    name: "2 Wheelers",
    slug: "2-wheelers",
    image: "",
    icon: "bike",
    sortOrder: 14,
    isActive: true,
    showInTopNav: true,
  },
];